### ISSUE TITLE
Unable to list or run stress test - getting below error

### ISSUE THREAD

**Issue by narendranss** [celery/cyanide#2]
Unable to list or run stress test - getting error in python 3.6.1

>C :\Users\naren>celery cyanide -l
> Traceback (most recent call last):
>   File "c:\users\naren\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\naren\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\naren\AppData\Local\Programs\Python\Python36-32\Scripts\celery.exe\__main__.py", line 9, in <module>
>   File "c:\users\naren\appdata\local\programs\python\python36-32\lib\site-packages\celery\__main__.py", line 14, in main
>     _main()
>   File "c:\users\naren\appdata\local\programs\python\python36-32\lib\site-packages\celery\bin\celery.py", line 326, in main
>     cmd.execute_from_commandline(argv)
>   File "c:\users\naren\appdata\local\programs\python\python36-32\lib\site-packages\celery\bin\celery.py", line 488, in execute_from_commandline
>     super(CeleryCommand, self).execute_from_commandline(argv)))
>   File "c:\users\naren\appdata\local\programs\python\python36-32\lib\site-packages\celery\bin\base.py", line 281, in execute_from_commandline
>     return self.handle_argv(self.prog_name, argv[1:])
>   File "c:\users\naren\appdata\local\programs\python\python36-32\lib\site-packages\celery\bin\celery.py", line 480, in handle_argv
>     return self.execute(command, argv)
>   File "c:\users\naren\appdata\local\programs\python\python36-32\lib\site-packages\celery\bin\celery.py", line 412, in execute
>     ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
>   File "c:\users\naren\appdata\local\programs\python\python36-32\lib\site-packages\celery\bin\base.py", line 285, in run_from_argv
>     sys.argv if argv is None else argv, command)
>   File "c:\users\naren\appdata\local\programs\python\python36-32\lib\site-packages\celery\bin\base.py", line 368, in handle_argv
>     return self(*args, **options)
>   File "c:\users\naren\appdata\local\programs\python\python36-32\lib\site-packages\celery\bin\base.py", line 244, in __call__
>     ret = self.run(*args, **kwargs)
>   File "c:\users\naren\appdata\local\programs\python\python36-32\lib\site-packages\cyanide\bin\cyanide.py", line 20, in run
>     return self.run_suite(names, **options)
>   File "c:\users\naren\appdata\local\programs\python\python36-32\lib\site-packages\cyanide\bin\cyanide.py", line 30, in run_suite
>     ).run(names, **options)
>   File "c:\users\naren\appdata\local\programs\python\python36-32\lib\site-packages\cyanide\suite.py", line 336, in run
>     tests = self.filtertests(group, names)[offset:numtests or None]
>   File "c:\users\naren\appdata\local\programs\python\python36-32\lib\site-packages\cyanide\suite.py", line 361, in filtertests
>     tests = self.groups[group]
> KeyError: 'all'

**Comment by jxltom** [comment]
It is because cyanide doesn't support python3 currently.
